= Spring Antora UI
// Settings:
:experimental:
:hide-uri-scheme:
// Project URLs:
:url-project: https://github.com/spring-io/antora-ui-spring
:url-ci-pipelines: {url-project}/pipelines
:img-ci-status: {url-project}/badges/master/pipeline.svg
// External URLs:
:url-antora: https://antora.org
:url-antora-docs: https://docs.antora.org
:url-git: https://git-scm.com
:url-git-dl: {url-git}/downloads
:url-gulp: http://gulpjs.com
:url-opendevise: https://opendevise.com
:url-nodejs: https://nodejs.org
:url-nvm: https://github.com/creationix/nvm
:url-nvm-install: {url-nvm}#installation
:url-source-maps: https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map

<p align="center">
  <a href="https://www.spring.io/">
    <img alt="Spring" src="https://spring.io/img/spring-2.svg" width="250" />
  </a>
</p>

image:https://github.com/spring-io/antora-ui-spring/actions/workflows/push.yml/badge.svg?branch=main[CI Status, link=https://github.com/spring-io/antora-ui-spring/actions/workflows/push.yml]

This project generates and packages the static resources that Spring uses for document production.

This project is based on https://antora.org[Antora].


== Development Quickstart

This section offers a basic tutorial to teach you how to preview it locally, and bundle it for use with Antora.
A more comprehensive tutorial can be found in the documentation at {url-antora-docs}.

=== Prerequisites

To preview and bundle the default UI, you need the following software on your computer:

* {url-git}[git] (command: `git`)
* {url-nodejs}[Node.js] (commands: `node` and `npm`)
* {url-gulp}[Gulp CLI] (command: `gulp`)

=== Preview the UI

The Spring Antora UI project is configured to preview offline.
The files in the [.path]_preview-src/_ folder provide the sample content that allow you to see the UI in action.
In this folder, you'll primarily find pages written in AsciiDoc.
These pages provide a representative sample and kitchen sink of content from the real site.

To build the UI and preview it in a local web server, run the `preview` command:

 $ npm install
 $ gulp preview

You'll see a URL listed in the output of this command:

....
[12:00:00] Starting server...
[12:00:00] Server started http://localhost:5252
[12:00:00] Running server
....

Navigate to this URL to preview the site locally.

While this command is running, any changes you make to the source files will be instantly reflected in the browser.
This works by monitoring the project for changes, running the `preview:build` task if a change is detected, and sending the updates to the browser.

Press kbd:[Ctrl+C] to stop the preview server and end the continuous build.

=== Package for Use with Antora

If you need to package the UI so you can use it to generate the documentation site locally, run the following command:

 $ gulp bundle

If any errors are reported by lint, you'll need to fix them.

When the command completes successfully, the UI bundle will be available at [.path]_build/ui-bundle.zip_.
You can point Antora at this bundle using the `--ui-bundle-url` command-line option.

If you have the preview running, and you want to bundle without causing the preview to be clobbered, use:

 $ gulp bundle:pack

The UI bundle will again be available at [.path]_build/ui-bundle.zip_.

== Extensions to the UI

=== Related Documentation

The UI presents a list of related documentation and that documentation can be filtered using two attributes:

* page-related-doc-categories - The categories to be included in the related documentation
* page-related-doc-projects - The project ids to be included in the related documentation

For a complete listing of valid categories and ids view https://github.com/spring-io/antora-ui-spring/blob/main/src/helpers/related_projects.js[related_projects.js]

The configuration is typically specified in asciidoc attributes section of the antora-playbook.yml:

.antora-playbook.yml
[source,yml]
----
asciidoc:
  attributes:
    # Include the projects with the security category
    page-related-doc-categories: security
    # Include the projects with ids framework and graphql
    page-related-doc-projects: framework,graphql
----

The Related Documentation links to the `All Docs...` page.
To include this resource, ensure that the https://github.com/spring-io/antora-extensions/blob/main/README.adoc[antora-extensions] is using 1.7.0+ and the https://github.com/spring-io/antora-extensions/blob/main/README.adoc#static-page[Static Page Extension] is included.

== Authors

Development of Antora is led and sponsored by {url-opendevise}[OpenDevise Inc].

== Copyright and License

Copyright (C) 2017-present OpenDevise Inc. and the Antora Project.

Use of this software is granted under the terms of the https://www.mozilla.org/en-US/MPL/2.0/[Mozilla Public License Version 2.0] (MPL-2.0).
See link:LICENSE[] to find the full license text.
